WIP: Parses invalid packages when using go modules
bitrise-steplib/steps-go-list pull request #3
Opened 2020-09-23 11:42 UTC by sylank

### Description of the issue
Go list step calls go list command to see the packages in a go project, but when the project has modules in it, it will install the dependencies first, which will mean additional line of text that the step understands as package.

### Context (optional)
When using on a go project with modules.

### Steps to reproduce:
Run the step on a go project that has modules.

### Actual result:
Dependency installation lines understood as package.
![image](https://user-images.githubusercontent.com/19280914/94007913-6c328180-fda2-11ea-94ad-cfe711ee50bf.png)

### Expected result:
Only real packages should be parsed and exported to the output package list env.

### Files to review
*

2020-09-24 15:12 UTC, zsolt-marta-bitrise requested changes
Looks ok 👍 I added a couple of improvement ideas and questions

2020-09-24 15:12 UTC, zsolt-marta-bitrise commented on main_test.go
> +	b := []string{"a", "b"}
Could you please name these more specifically? like `original` and `excludes`

2020-09-24 15:12 UTC, zsolt-marta-bitrise commented on main_test.go
> +	assert.Equal(t, filteredLines.Expected, diffResult.Expected)
I'd add also the assertion for the `Removed` items

2020-09-24 15:12 UTC, zsolt-marta-bitrise commented on gotool/gotool_test.go
> +	testCases := []struct {
This method is a bit bloaty and hard to read. I suggest moving out the test cases definition to clear it up

2020-09-24 15:12 UTC, zsolt-marta-bitrise commented on gotool/gotool_test.go
> +	ExecuteCommandFn func(command string, args ...string) (string, error)
While this looks a pretty good custom solution, I'd urge you to take a look at [testify](https://github.com/stretchr/testify), which provides a standard way of mocking objects.
For an example usage, take a look here: https://github.com/bitrise-io/beitris/pull/38/files#diff-8d6851f3ab5c8373ede6234121198af8

2020-09-24 15:12 UTC, zsolt-marta-bitrise commented on gotool/gotool.go
> +func (c CommandExecutor) ExecuteCommand(stringCommand string, args ...string) (string, error) {
Can we integrate this into `"github.com/bitrise-io/go-utils/command"` somehow? I'm afraid that these additional layers will get added to more repos and we forget about them and that leaves a lot of inconsistent duplicate code.
If not, can we check if we really need this new type?

2020-09-24 15:12 UTC, zsolt-marta-bitrise commented
Thanks for the description, especially the files to cover 😎 ! Can you please also include the jira ticket 🙏 ?

2020-09-25 11:04 UTC, sylank commented
> Thanks for the description, especially the files to cover 😎 ! Can you please also include the jira ticket 🙏 ?

We don't copy the Jira card ID because this is an open-source project. It won

2020-09-25 11:08 UTC, sylank commented
> Thanks for the description, especially the files to cover 😎 ! Can you please also include the jira ticket 🙏 ?

We don't copy the Jira card URL into the open-source project's PR because it doesn't give any useful information for the outside contributors and our tracking system is internal.
We are planning to create an external(open) issue board.
I set the Jira card ID and the GitHub integration will connect the card and the PR.

2020-09-25 11:24 UTC, zsolt-marta-bitrise commented on gotool/gotool.go
> +func (c CommandExecutor) ExecuteCommand(stringCommand string, args ...string) (string, error) {
Let's not block this PR for now, but in the future we should come up with a common solution for this

2020-09-25 11:54 UTC, zsolt-marta-bitrise approved these changes
Thanks for the changes 🥇

2020-09-25 13:04 UTC, trapacska requested changes

2020-09-25 13:04 UTC, trapacska commented on bitrise.yml
> +      - path::./:
please add another test in which it is reproducing the original issue

2020-09-28 10:31 UTC, trapacska approved these changes

2020-09-28 10:40 UTC, merged